version: '3'
services: 
  # grav:
  #   image: grav:latest
  #   volumes: 
  #     - ./:/var/www/html
  #   restart: always
  
  nginx:
    image: nginx:latest
    ports: 
      - 8080:8080
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./grav:/var/www/html
    restart: always

  php:
    image: php:7.4-fpm

  