version: '3'
services: 
  web:
    image: nginx:latest
    ports: 
      - 8080:80
    volumes:
      - ./conf/grav.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on: 
      - app

  app:
    image: grav
    volumes: 
      - ./:/var/www/html
    restart: always